### Local
POST http://localhost:8000/api/chat/
Content-Type: application/json

{
  "history": [
    {
      "content": "What is the main field of expertise of the XYZ company?",
      "role": "user"
    }
  ]
}

### Local
POST http://localhost:8000/api/documents/re-vectorize-from-storage


### Local
GET http://localhost:8000/api/version


### Cloud
GET https://<specify external ip or host>/api/version
Authorization: Bearer <specify token>

### Cloud
POST https://<specify external ip or host>/api/chat/
Authorization: Bearer <specify token>

{
  "history": [
    {
      "content": "What is the main field of expertise of the XYZ company?",
      "role": "user"
    }
  ]
}
