### Local
POST http://localhost:8000/api/chat/
Content-Type: application/json

{
  "history": [
    {
      "content": "What is the main field of expertise of the XYZ company?",
      "role": "user"
    }
  ]
}

### Local
POST http://localhost:8000/api/documents/re-vectorize-from-storage


### Local
GET http://localhost:8000/api/version


### Cloud
GET https://<please specify>/api/version
Authorization: Bearer <please specify>

### Cloud
POST https://<please specify>/api/chat/
Content-Type: application/json
Authorization: Bearer <please specify>

{
  "history": [
    {
      "content": "What is the main field of expertise of the XYZ company?",
      "role": "user"
    }
  ]
}

### Cloud
POST https://<please specify>/api/documents/re-vectorize-from-storage
Authorization: Bearer <please specify>
