### Local
POST http://localhost:8000/api/chat/
Content-Type: application/json

"Hi. Who are you? Please introduce yourself."


### Local
GET http://localhost:8000/api/version


### Cloud
POST https://<specify external ip or host>/api/chat/
Authorization: Bearer <specify token>

"Hi. Who are you? Please introduce yourself."
