name: Build and Push Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/etvt/aitestdrive:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login to Google Cloud
        id: 'google-cloud-auth'
        if: github.event_name != 'pull_request'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
         project_id: '${{ env.PROJECT_ID }}'

      - name: Docker auth
        run: |-
          gcloud auth configure-docker gcr.io

      - name: Build and push Docker image to GCR
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: gcr.io/${{ env.PROJECT_ID }}/aitestdrive:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
